### ISSUE TITLE
Contributor list screen

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#115]
## Overview (Required)

 - We should implement contributor list screen
 - I want this feature early for contributor motivation.
![image](https://user-images.githubusercontent.com/1386930/72246256-a81f1f80-3635-11ea-9307-533317cbd8c4.png)

## Links	

-

**Comment by mkano9** [comment]
@roana0229 @takahirom Can I take this one? :raised_hand:

**Comment by satsukies** [comment]
@mkano9 Of course, thank you! Assigned :bow:

**Comment by takahirom** [comment]
Thank you as always!! 🎉

**Comment by mkano914** [comment]
Hi @roana0229, what does the number next to the profile image represent? Is it like a rank in the order of who has contributed the most? 

Looking at the API response, I see `sort`, but it seems to be a unique number at the moment. In the cases of Kendasha Wood and Sun Jun in your design comp, there are no numbers next to them because they are all supposed to have `sort` value of 3?
https://deploy-preview-49--droidkaigi-api-dev.netlify.com/2020/contributors/index.json

**Comment by mkano9** [comment]
Hi @roana0229, what does the number next to the profile image represent? Is it like a rank in the order of who has contributed the most? 

Looking at the API response, I see `sort`, but it seems to be a unique number at the moment. In the cases of Kendasha Wood and Sun Jun in your design comp, there are no numbers next to them because they are all supposed to have `sort` value of 3?
https://deploy-preview-49--droidkaigi-api-dev.netlify.com/2020/contributors/index.json

**Comment by roana0229** [comment]
@mkano9 Hi 😄 

Contributor number is [this page](https://github.com/DroidKaigi/conference-app-2020/graphs/contributors) rank.

I'm sorry. API response is WIP.
All contributor has rank and display `sort` numbers after 3 too.

Please feel free to ask us if you have any questions 👍

**Comment by mkano9** [comment]
Thanks for the clarification. I will display `sort`.
