### ISSUE TITLE
iOS App floor map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#137]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Since the event venue is large, I think it would be more convenient to have a floor map.

 ## Links	

-

**Comment by entaku19890818** [comment]
Can I try it?

**Comment by yurihondo** [comment]
Yes of course!
Thanks! Assined:D

**Comment by entaku19890818** [comment]
![image](https://user-images.githubusercontent.com/9211010/73133482-70b86600-406c-11ea-9bf1-4c25ec8e2591.png)

I think this is floor map design.
What does the locaicion mark mean?
Users current location?

**Comment by takahirom** [comment]
We can open map from session detail. We can use pin. 
But now we don't have to use pin🙏

**Comment by entaku19890818** [comment]
I see!
First, I make it possible to display the map image.

**Comment by entaku19890818** [comment]
I will send a pull request.
Here's what I thought was a problem.

- The title is not displayed because it did not seem to be multilingual.
- The SideNavigationBar should have state. The menu currently selected cannot be highlighted.
- Is it better to create a common ViewController? everyone wants to use setUpAppBar.

**Comment by ry-itto** [comment]
@entaku19890818 
Thanks for your PR. 😄 

> I will send a pull request.
> Here's what I thought was a problem.
> 
> * The title is not displayed because it did not seem to be multilingual.

Yes, exactly. I'm going to do it after implementing all views.

> * The SideNavigationBar should have state. The menu currently selected cannot be highlighted.
> * Is it better to create a common ViewController? everyone wants to use setUpAppBar.

I'm sorry.. I missed about this. 
Please add `shared` static property for `SidebarViewController` or add argument(`SwitchViewControllerType`) to `SidebarViewController`'s initializer? 
(I think `SideNavigationBar` represents `SidebarViewController`.)

I think last one is better because set default selection value is executed in `viewDidAppear` call.

**Comment by ry-itto** [comment]
@entaku19890818 
> * The SideNavigationBar should have state. The menu currently selected cannot be highlighted.

Please add Sidebar's state for `SidebarViewController` in your PR or another PR. 🙏 

> * Is it better to create a common ViewController? everyone wants to use setUpAppBar.

I think it is good to create a `**ViewController` class with an `AppBar` that inherits `UIViewController`. Please modify this with above 🙏

**Comment by entaku19890818** [comment]
> Please add Sidebar's state for SidebarViewController in your PR or another PR. 
Add the this PR. Please check it.

> think it is good to create a **ViewController class with an AppBar that inherits UIViewController. Please modify this with above 🙏
Add ContentViewController in Common.

Please tell me if you have any problems.
👍
