### ISSUE TITLE
Session crap or thumbs up feature

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#201]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- We may adopt a thumbs-up or crap function this year instead of a session survey for several reasons.
- What to do with the UI?
- Is it better to use something like Distributed Counter?
https://firebase.google.com/products/extensions/firestore-counter

 ## Links	

-

**Comment by surajsau** [comment]
We can do two things:
- if app is not in foreground, we can schedule a notification saying 'Take survey'. Clicking this would take the user to the dialog listing all the sessions in the last hour and ask user to rate them (Good, Bad, not attended)
- if app is in foreground, we can show the same dialog above

Scheduling of this notification/dialog can be like
- 5 minutes after the user's My Plan session has ended
- 5 minutes after each hour (generally since each session is about 1 hour long)

The static scheduling part can be pre-configured in the app. The My Plan sessions can be dynamically scheduled.

**Comment by takahirom** [comment]
In this DroidKaigi we are thinking about crap or like, not session survey.

**Comment by takahirom** [comment]
I will update this issue. We are talking with designer.

**Comment by takahirom** [comment]
I will create new issue
