### ISSUE TITLE
When come back to search screen after query searching, editText become empty

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#348]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Should retype queried text from saved at viewModel instance.
    - Currently, search result list is displaying filtered list when coming back.

 ## Links	
👀 
https://github.com/DroidKaigi/conference-app-2020/blob/7e4a56cc15be5cca58c7f8c70d72ad810fecb344/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SearchSessionsViewModel.kt#L19

**Comment by nredjap** [comment]
I want to try repair this issue.🙋
I'll code now.
(I contribute OSS for the first time. If I cause trouble, sorry...)

Because I can not english well, I write Japanese that want to tell in below...↓
英語まともに書けているかわからないので、言いたい日本語も添えて
おきます...↓

このIssueの修正に取り組みたいです。🙋
これから作業をします。
(初めてOSSコントリビュートをします。もし迷惑をかけたらすみません...)

**Comment by roana0229** [comment]
Of course, assigned 👍 
Please feel free to contact us if you have any questions.
