### ISSUE TITLE
Web development environment support

### ISSUE THREAD

**Issue by itome** [DroidKaigi/conference-app-2020#641]
## Kind (Required)

- Other

## Overview (Required)
I'm developing unofficial flutter app for droidkaigi and it's also supporting web, but api request blocked by CORS.
Can this project support web local development environment?

## Links
https://github.com/itome/droidkaigi_flutter

**Comment by takahirom** [comment]
Probably @jmatsu ??

**Comment by jmatsu** [comment]
I'm unsure if it's feasible because of the hosting service. Honestly speaking, I cannot have enough time to work on the API side by the event date, for now.

I'm thinking one workaround is to use a proxy server for CORS. It may work at least during your development. However, please note that we cannot guarantee anything of the CORS proxy services and what will happen while using them. I apologize.

**Comment by itome** [comment]
Thank you for your quick reply! I'll try proxy server.

**Comment by jmatsu** [comment]
@itome 
I could see `curl -v 'https://api.droidkaigi.jp/2020/contributors' > /dev/null` returned a CORS header that allows all origins but it caused redirecting to an URL that has an insecure protocol. I'm unsure the problem you've faced is CROS or mixed content though, please try to add `/` to the URLs to be called like `https://api.droidkaigi.jp/2020/contributors/`
