### ISSUE TITLE
All dependent libraries are not enumerated in License Activity.

### ISSUE THREAD

**Issue by rkonno** [DroidKaigi/conference-app-2020#713]
**Overview (Required)**
- The License page of this app uses [oss-licenses-plugin](https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin).
- Currently, there is a problem that all dependent libraries are not enumerated.
- The cause is probably due to the composition of the multi-module project.
- Related issues
  - google/play-services-plugins#7
  - google/play-services-plugins#25

**Steps To Reproduce**
- Run DroidKaigi 2020
- Open `License` page from `About` page.
- Only some dependent libraries are listed

**Env(specified version):**
- `play-services-oss-licenses` -> `17.0.0`
- `oss-licenses-plugin` -> `0.10.0`

**Additional context**
- Previous isssue and pull request #555 / #687

**Comment by clockvoid** [comment]
I tried to watch licenses page with app from DeployGate, but there are no licenses.
Even if I use [this](https://deploygate.com/distributions/7fae15f61fadfdd2a4232f81206d9d6bb21eee5c) version, it shows no license.
I think in CI's release build, generateLicenses is failed.
If this issue is known, I'm sorry to repeat.

<img src="https://user-images.githubusercontent.com/6965122/73807412-b95fe400-480f-11ea-84c6-3ab6cf99c704.png" width="300">

**Comment by nashcft** [comment]
@clockvoid 
It seems that the color of texts and dividers is set to white when dark theme is applied.

**Comment by clockvoid** [comment]
@nashcft 
Oh, I see.
You’re right, it visible with the light theme🤣

**Comment by koji-1009** [comment]
Hi, `0.10.2` is released!

https://developers.google.com/android/guides/releases#march_09_2020

> - The latest update to the OSS licenses Gradle plugin includes fixes for the following issues:
>   - Failure to find any licenses when a library project is present (GitHub Issue #119)
>   - Ambiguous method overloading when POM file cannot be resolved (GitHub Issue #120)

**Comment by takahirom** [comment]
Nice 👍
